version: "3.8"

services:
  database: 
    image: mysql:8.0.28
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  server:
    depends_on:
      - database
    build: ./src
    restart: "unless-stopped"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    stdin_open: true
    tty: true
    